### ISSUE TITLE
Question - laravel implementation 

### ISSUE THREAD

**Issue by Nizari** [tobyzerner/json-api-server#14]
Hé @tobyzerner ,

So far compliments for this amazing looking package. I was wondering if you use this for laravel and if so, where and how you implement your schema definition. Do you make it a simpleton?

I’ll try to get this proposed at our company so we might even assist in helping you with this package if you would appreciate that.

**Comment by tobyzerner** [comment]
Hi @Nizari, thank you for the kind words!

I suggest to make a route (or controller) in `routes/api.php` as follows:

```php
Route::any('{uri}', function (ServerRequestInterface $request) {
    $api = new JsonApi(url('/api'));
    
    if (Auth::check()) {
        $request = $request->withAttribute('actor', Auth::user());
        $api->authenticated();
    }
    
    $resources = [
        'posts' => Post::class,
        'comments' => Comment::class,
        'users' => User::class,
    ];
    
    foreach ($resources as $name => $model) {
        $api->resource($name, new EloquentAdapter(new $model), function (Type $type) use ($name) {
            require __DIR__."/../schema/$name.php";
        });
    }
    
    try {
        return $api->handle($request);
    } catch (Throwable $e) {
        if (! $e instanceof ErrorProviderInterface) {
            throw $e;
        }
    
        return $api->error($e);
    }
})->where('uri', '.*');
```

Then put your schema definitions in eg `schema/posts.php`.

You'll need to install the Symfony HTTP Message Bridge as per the [Laravel docs](https://laravel.com/docs/6.x/requests#psr7-requests).

Hope that helps, let me know if you have any further questions!

**Comment by Nizari** [comment]
Thank you very much! I'll take a schot at it. Keep up the good work!
