### ISSUE TITLE
Question - filter by relationship and scope argument 

### ISSUE THREAD

**Issue by smtlab** [tobyzerner/json-api-server#35]
Thank you for starting this awesome project.

I was able to implement adapter for Doctrine ORM with query builder, was able to implement most of the methods with ease, which mostly works like charm.

However, I see you are passing `$scope` which is Closure as the third argument in `filterByRelationship`. I think this is too coupled with Laravel's Eloquent. 

How can I access filters col and values for relationships?

```
    /**
     * Manipulate the query to only include resources with a relationship within
     * the given scope.
     */
    public function filterByRelationship($query, Relationship $relationship, \Closure $scope): void
    {
        $query->join(self::ALIAS . '.' . $relationship->getType(), $relationship->getType());
        // How will I get filter parameters for the relationship?
        $query->where($relationship->getType() . '.filterCol = :filterCol');
        $query->setParameter('filterCol', $filterValue);
    }
```

My suggestion would be to maintain the filter parameters in an array or collection and provide the same in `filterByRelationship` method

**Comment by tobyzerner** [comment]
Hey @smtlab, thanks for the question. Glad to hear your Doctrine implementation is coming along!

Yes I wondered whether this would be too Eloquent-specific. The advantage of passing a `$scope` Closure is that it makes supporting nested relationship filters trivial – at least in Eloquent, which builds subqueries to support this kind of filtering.

I'm not familiar with Doctrine, but I'm wondering whether it would be possible for you to create a new query builder object, pass it into `$scope` (which will in turn be passed into `filterByIds` and `filterByAttribute`), and then extract the column values from that query builder and apply them to the parent query? Something like:

```php
public function filterByRelationship($query, Relationship $relationship, \Closure $scope): void
{
    $relationshipQuery = new QueryBuilder();
    $scope($relationshipQuery);

    $query->join(self::ALIAS . '.' . $relationship->getName(), $relationship->getName());

    foreach ($relationshipQuery->wheres as $key => $value) {
        $query->where($relationship->getName().".$key = :{$key}Value");
        $query->setParameter("{$key}Value", $value);
    }
}
```

**Comment by smtlab** [comment]
@tobyzerner  Thanks for your comment, I tried the approach, I passed the same parent `$query` to the scope method instead of the new query builder instance, which in turn is passed into `filterByIds`, the problem here is I just need to prefix the filter column with relationship property then it works perfectly.

```php
    /**
     * Manipulate the query to only include resources with the given IDs.
     */
    public function filterByIds($query, array $ids, Relationship $relation): void
    {    
        $alias = $relation ? $relation->getProperty() : self::ALIAS;
        $query->where($alias . '.id', $ids);
    }

    /**
     * Manipulate the query to only include resources with a certain attribute
     * value.
     *
     * @param string $operator The operator to use for comparison: = < > <= >=
     */
    public function filterByAttribute($query, Attribute $attribute, $value, string $operator = '=', Relationship $relation): void
    {
        $alias = $relation ? $relation->getProperty() : self::ALIAS;
        $query->where( $alias . '.' . $attribute, $operator, $value);
    }

    /**
     * Manipulate the query to only include resources with a relationship within
     * the given scope.
     */
    public function filterByRelationship($query, Relationship $relationship, \Closure $scope): void
    {
            $query->join(self::ALIAS . '.' . $relationship->getProperty(), $relationship->getProperty());
            $scope($query);
    }

```

**Comment by smtlab** [comment]
I have fixed the issue by accessing the relation alias from the `$query` object itself :)
I Will create a PR soon for the Doctrine adapter, also it would be better if you move the Eloquent adapter classes in a folder specific to Eloquent `Adapter/Eloquent`. So new adapters can follow the same naming convention `Adapter/DoctrineOrm`

**Comment by tobyzerner** [comment]
Perfect, sounds good!

I think I'm happy for all adapters to sit directly in the `Adapter` namespace (ie. `JsonApi\Adapter\DoctrineOrmAdapter`).
