### ISSUE TITLE
Updatable resource, wrong documentation

### ISSUE THREAD

**Issue by AzenoX** [tobyzerner/json-api-server#46]
Hello ;)

I recently implement your package in a laravel project I'm working on, and I faced an issue^^

I tried to use "updatable" for my resource by following this [https://tobyzerner.github.io/json-api-server/update.html](https://tobyzerner.github.io/json-api-server/update.html)
`$type->updatable(fn(Context $context) => self::authorize($context));`

But I got this error:
`Argument #1 ($context) must be of type Tobyz\JsonApiServer\Context, App\Models\MyModel given`

After a few research in the code, I found something.
In Endpoint/Update.php (line 35), you evaluate if the resource can be updated or not:
`evaluate($schema->isUpdatable(), [$model, $context])`
On this line, you have **$model** and $context.

So yeah, to me, we need to add **$model** in the closure as well like this:
`$type->updatable(fn($model, Context $context) => self::authorize($context));`

There may be another way to achieve this, but that's what I found. 
If I'm right, you should update the documentation :D

**Comment by tobyzerner** [comment]
The docs have been rewritten for v1.0.0-alpha.1, and this is fixed.
