### ISSUE TITLE
Missing/broken documentation?

### ISSUE THREAD

**Issue by bertramakers** [tobyzerner/json-api-server#67]
Hi! We're looking for a PHP library to implement the JSON:API specification for a new API version in an existing project that uses a combination of various composer packages for routing and request handling. 

This library looks very promising as we can drop it in our existing setup if I understand correctly (we're using a PSR-7 compatible router), and it seems that we can provide our own adapters for our data models. It also looks very feature complete at first glance.

However a lot of the pages in the documentation seem to be missing or broken? For example "Adapters", "Scopes", "Attributes" and others load indefinitely if I click on them in the menu, or return a 404 if I browse to their URL directly. Is this documentation available somewhere, or is it missing for the moment?

Sorry if this project is not ready for production usage yet, I found it via https://jsonapi.org/implementations/#server-libraries-php (it's even the first one in the list)

**Comment by tobyzerner** [comment]
Hi @bertramakers, thanks for your interest in the lib!

I actually just finished up a major rewrite and tagged a new version a couple hours ago ([1.0.0-alpha.1](https://github.com/tobyzerner/json-api-server/releases/tag/v1.0.0-alpha.1)). The docs have been overhauled too so it sounds like you're getting a cached version of the old docs. Can you clear your browser cache and [try loading them](https://tobyzerner.github.io/json-api-server/) again?

You can also [browse the raw docs](https://github.com/tobyzerner/json-api-server/tree/v0.2.0/docs) for the previous version, but I would highly recommend trying out the new version as the new API is quite significantly different (and better).

I hope to move it forward to a stable 1.0 release relatively quickly – please let me know if you run into any issues, have any questions, or notice gaps in the docs!

**Comment by bertramakers** [comment]
Thanks for the quick response @tobyzerner ! When I visited the documentation again just now, the navigation menu was different from before. I guess GitHub's CDN still had to catch up 😄 It looks very clear at first glance, so I'll give it a shot and let you know if I run into any problems/questions in a follow-up issue. 👌
