### ISSUE TITLE
"Typed property Tobyz\...\BadRequestException::$sourceType must not be accessed before initialization"

### ISSUE THREAD

**Issue by bertramakers** [tobyzerner/json-api-server#69]
Encountered this while sending some requests to test out some functionality.

Steps to reproduce:

1. Set up a JsonApi request handler with at least one resource type that is creatable
2. Send a `POST` request to create a new resource, but do not include a body or set it to `{}`

What happens: 
A fatal error in `BadRequestException`  is not caught, and in the case of our app it is returned as:
```
{
  "status_code": 500,
  "reason_phrase": "Typed property Tobyz\\JsonApiServer\\Exception\\BadRequestException::$sourceType must not be accessed before initialization"
}
```
In your case it may be returned differently in the response, added to a log file, ...

The cause seems to be that the `$sourceType` property it is accessed here, but because the error does not have a defined "source" that property has not been set (i.e. initialized): https://github.com/tobyzerner/json-api-server/blob/main/src/Exception/BadRequestException.php#L37

When I patch `BadRequestException` to give `$sourceType` a default value (an empty string for example), I instead get:

```
{
  "errors": [
    {
      "title": "Bad Request",
      "status": "400",
      "detail": "data must be an object"
    }
  ],
  "jsonapi": {
    "version": "1.1"
  }
}
```

This seems like the expected result, unless this missing `data` property should also result in a "source" being present in the error? In which case the fix should probably be calling `setSourcePointer()` if it is missing or not an object.

Note: The same error happens when you provide a `data` object but omit `type` inside of it.

**Comment by tobyzerner** [comment]
Hey @bertramakers, thanks for the detailed report. I've just pushed a commit which should fix this issue and generally improve the reliability of the `source` member in Bad Request errors (though haven't written tests for it).
