### ISSUE TITLE
Allow custom type resolution when creating polymorphic relationships

### ISSUE THREAD

**Issue by bertramakers** [tobyzerner/json-api-server#72]
As mentioned in https://github.com/tobyzerner/json-api-server/issues/68#issuecomment-1609350773, I use simple `stdClass` objects to represent my data models inside the `Resource` classes.

I'm now trying to create a polymorphic `ToOne` relationship like this:

```
ToOne::make('example')
    ->type([
        'type1',
        'type2'
    ])
     ->required()
     ->writable()
     ->includable(),
```

The example types `type1` and `type2` are also registered as resources on the `JsonApi` class.

Now when I try to create a new instance of a resource with this relationship, I get:

```
No resource type defined to represent model stdClass
```
(Thrown here: https://github.com/tobyzerner/json-api-server/blob/main/src/Serializer.php#L156-L158)

It seems to me that the `Serializer` is trying to determine the resource class related to the included model, but because it's always `stdClass` it cannot differentiate between the various models being returned.

Taking a closer look at the documentation, I see that I should also define the model classes as keys in the `type()` call: https://tobyzerner.github.io/json-api-server/relationships.html#polymorphic-relationships

However, since all my models are plain `stdClass` objects, this is obviously not possible.

Is there a workaround possible, aside from creating a class for every one of my models? As mentioned in the previously linked issue I didn't do that because we already have classes for all of our models, but they're not usable in `newModel()` because they have some required properties that are not available there. And introducing a second class for every model is a lot of extra work.

~Looking at the `Serializer::addIncluded()` that calls `resourceForModel()`, I see that `$model` is also available there and it already contains the `type` as a property (at least in our case).~ Edit: This was because of how we used to implement our models.

**Comment by tobyzerner** [comment]
How about if I add the ability to define a callback within a relationship definition, that resolves a related model to its resource type. Something like this:

```php
ToOne::make('example')
    ->type(['type1', 'type2'])
    ->resolve(fn($model) => $model->foo ? 'type1' : 'type2'),
```

**Comment by tobyzerner** [comment]
I've got a more comprehensive solution for this one coming soon!

**Comment by tobyzerner** [comment]
With the recent addition of Collections there are now two solutions for this.

1. Implement a Collection for the polymorphic relationship. A Collection describes which resource types are available and also implements logic to resolve a model to its resource type.

```php
use Tobyz\JsonApiServer\Resource\CollectionInterface;

class FooCollection implements CollectionInterface
{
    public function name(): string
    {
        return 'foo';
    }

    public function resources(): array
    {
        return ['type1', 'type2'];
    }

    public function resource(object $model, Context $context): ?string
    {
        return $model->foo ? 'type1' : 'type2';
    }

    public function endpoints(): array
    {
        return [];
    }
}
```

```php
$api->collection(new FooCollection());
```

```php
ToOne::make('example')
     ->collection('foo')
     ->required()
     ->writable()
     ->includable()
```

2. Every class that extends the base `Resource` class is actually also a Collection which resolves to itself. You can customise the resolution logic in each of your resources to return `null` if a given model does NOT correspond to the resource. Then, provide an array of the resources (collections) when defining the relationship - the model will resolve to the first non-null resource.

```php
use Tobyz\JsonApiServer\Resource\Resource;

class Type1Resource extends Resource
{
    // ...

    public function resource(object $model, Context $context): ?string
    {
        return $model->foo ? $this->type() : null;
    }
}

class Type2Resource extends Resource
{
    // ...

    public function resource(object $model, Context $context): ?string
    {
        return $model->bar ? $this->type() : null;
    }
}
```

```php
ToOne::make('example')
     ->type(['type1', 'type2']) // "type" is now just an alias for "collection"
     ->required()
     ->writable()
     ->includable()
```

**Comment by tobyzerner** [comment]
Docs updated
