### ISSUE TITLE
`Integer` is missing `minimum()`, `maximum()` and `multipleOf()`

### ISSUE THREAD

**Issue by bertramakers** [tobyzerner/json-api-server#77]
Looking at the documentation for [Number and Integer](https://tobyzerner.github.io/json-api-server/attributes.html#number-and-integer), I'd assume that `Integer` would also have the `minimum()`, `maximum()` and `multipleOf()` methods that `Number` does.

Easiest fix would probably be to copy them to `Integer`, but it would be a bit of duplicate code.

**Comment by tobyzerner** [comment]
Just make sure you're on the latest - this should've already been fixed in 11fafff. (Added some more unit tests just now c4115be14d0d9f610c24b4d688145cf56dbc196d)

**Comment by bertramakers** [comment]
I missed the recent release, that fixed it indeed 👍
